
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviestore-client
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moviestore-client
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviestore-api
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /swagger/
        pathType: Prefix
        backend:
          service:
            name: moviestore-api
            port:
              number: 8080
---