apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sqlserver
  template:
    metadata:
      labels:
        component: sqlserver
    spec:
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlpassword
                  key: MSSQLPASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql/data
              subPath: mssql


             
